name: gnsp
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.18
  - pytorch=2.3.1
  - pytorch-cuda=11.8
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - matplotlib=3.7.2
  - numpy=1.24.3
  - pip:
      - accelerate==1.0.1
      - transformers==4.46.3
      - datasets==3.1.0
      - scikit-learn==1.3.2
      - seaborn==0.13.2
